stages:
  - terraform
  - ansible

variables:
  TF_INPUT: false
  VBOX_MACHINES_DIR: "C:/VMs"

terraform:
  stage: terraform
  script:
    - terraform init
    - terraform apply -auto-approve
  artifacts:
    paths:
      - ansible/terraform_output.json

ansible:
  stage: ansible
  script:
    - apt-get update && apt-get install -y ansible python3
    - cd ansible/
    - python3 generate_inventory.py
    - ansible-playbook -i inventory playbook.yml
  dependencies:
    - terraform
