apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: kyratech-prova
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Assicurati che corrisponda alla storage class del PVC
  hostPath:
    path: /mnt/data/mysql