apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc   # Il nome del PVC può rimanere 'mysql-pvc'
  namespace: kyratech-prova
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard  # Deve essere lo stesso nome della storage class nel PV
