- name: Setup Prometheus and Grafana using Helm and Kubernetes
  hosts: masters
  tasks:
    - name: Add Prometheus Helm repository
      command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Add Grafana Helm repository
      command: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Update Helm repositories
      command: helm repo update

    - name: Install Prometheus
      command: helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace

    - name: Apply Alertmanager Persistent Volume
      command: kubectl apply -f /tmp/automazione/prometheus/alertmanager-pv.yaml

    - name: Apply Prometheus Server Persistent Volume
      command: kubectl apply -f /tmp/automazione/prometheus/prometheus-server-pv.yaml

    - name: Port forward Prometheus Server
      command: kubectl port-forward -n monitoring svc/prometheus-server 9090:80 &
      async: 30
      poll: 0

    - name: Install Grafana
      command: helm install grafana grafana/grafana --namespace monitoring

    - name: Port forward Grafana
      command: kubectl port-forward -n monitoring svc/grafana 3000:80 &
      async: 30
      poll: 0

    - name: Retrieve Grafana admin password
      command: kubectl get secret -n monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode
      register: grafana_password

    - name: Display Grafana admin password
      debug:
        msg: "Grafana admin password: {{ grafana_password.stdout }}"
