- hosts: master.example.com
  become: yes
  gather_facts: false
  tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: Check if node is already part of the cluster
      shell: kubectl get nodes {{ inventory_hostname }} --no-headers
      register: node_status
      ignore_errors: true

    - name: Skip join if node is already part of the cluster
      debug:
        msg: "Node {{ inventory_hostname }} is already part of the cluster."
      when: node_status.rc == 0

    - name: Reset kubeadm to remove the node from the cluster
      shell: kubeadm reset -f
      when: ansible_facts['distribution'] == "Ubuntu" and node_status.rc != 0  # Proceed only if node is not already part of the cluster

    - name: Remove old node_joined.txt file
      file:
        path: "{{ ansible_env.HOME }}/node_joined.txt"
        state: absent
      when: ansible_facts['distribution'] == "Ubuntu" and node_status.rc != 0  # Only remove the file if node is not already part of the cluster

    - name: Join the cluster again
      shell: "{{ hostvars['master.example.com'].join_command }} --ignore-preflight-errors all >> {{ ansible_env.HOME }}/node_joined.txt"
      args:
        chdir: "{{ ansible_env.HOME }}"
      when: node_status.rc != 0  # Only join if node is not already part of the cluster
