- hosts: master.example.com
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: reset kubeadm to remove the node from the cluster
      shell: kubeadm reset -f
      when: ansible_facts['distribution'] == "CentOS"  # aggiungi la condizione per il tuo sistema operativo, se necessario

    - name: remove old node_joined.txt file
      file:
        path: "{{ ansible_env.HOME }}/node_joined.txt"
        state: absent
      when: ansible_facts['distribution'] == "CentOS"  # aggiungi la condizione per il tuo sistema operativo, se necessario

    - name: join cluster again
      shell: "{{ hostvars['master.example.com'].join_command }} --ignore-preflight-errors all >> {{ ansible_env.HOME }}/node_joined.txt"
      args:
        chdir: "{{ ansible_env.HOME }}"

