- name: Configure all hosts
  hosts: all
  tasks:
    - name: Ensure SSH is installed
      apt:
        name: openssh-server
        state: present
        update_cache: true

    - name: Add SSH key to authorized_keys
      authorized_key:
        user: root
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
